package com.kaadas.lock.utils.greenDao.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 27): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 27;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        WifiLockInfoDao.createTable(db, ifNotExists);
        ProductInfoDao.createTable(db, ifNotExists);
        GatewayLockServiceInfoDao.createTable(db, ifNotExists);
        CateEyeInfoBaseDao.createTable(db, ifNotExists);
        GatewayBaseInfoDao.createTable(db, ifNotExists);
        CatEyeEventDao.createTable(db, ifNotExists);
        DevicePowerDao.createTable(db, ifNotExists);
        GatewayPasswordPlanBeanDao.createTable(db, ifNotExists);
        PirDefaultDao.createTable(db, ifNotExists);
        CatEyeServiceInfoDao.createTable(db, ifNotExists);
        BleLockServiceInfoDao.createTable(db, ifNotExists);
        GatewayServiceInfoDao.createTable(db, ifNotExists);
        GatewayLockRecordDao.createTable(db, ifNotExists);
        GatewayLockBaseInfoDao.createTable(db, ifNotExists);
        GatewayLockPwdDao.createTable(db, ifNotExists);
        GatewayLockAlarmEventDaoDao.createTable(db, ifNotExists);
        DBOpenLockRecordDao.createTable(db, ifNotExists);
        HistoryInfoDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        WifiLockInfoDao.dropTable(db, ifExists);
        ProductInfoDao.dropTable(db, ifExists);
        GatewayLockServiceInfoDao.dropTable(db, ifExists);
        CateEyeInfoBaseDao.dropTable(db, ifExists);
        GatewayBaseInfoDao.dropTable(db, ifExists);
        CatEyeEventDao.dropTable(db, ifExists);
        DevicePowerDao.dropTable(db, ifExists);
        GatewayPasswordPlanBeanDao.dropTable(db, ifExists);
        PirDefaultDao.dropTable(db, ifExists);
        CatEyeServiceInfoDao.dropTable(db, ifExists);
        BleLockServiceInfoDao.dropTable(db, ifExists);
        GatewayServiceInfoDao.dropTable(db, ifExists);
        GatewayLockRecordDao.dropTable(db, ifExists);
        GatewayLockBaseInfoDao.dropTable(db, ifExists);
        GatewayLockPwdDao.dropTable(db, ifExists);
        GatewayLockAlarmEventDaoDao.dropTable(db, ifExists);
        DBOpenLockRecordDao.dropTable(db, ifExists);
        HistoryInfoDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(WifiLockInfoDao.class);
        registerDaoClass(ProductInfoDao.class);
        registerDaoClass(GatewayLockServiceInfoDao.class);
        registerDaoClass(CateEyeInfoBaseDao.class);
        registerDaoClass(GatewayBaseInfoDao.class);
        registerDaoClass(CatEyeEventDao.class);
        registerDaoClass(DevicePowerDao.class);
        registerDaoClass(GatewayPasswordPlanBeanDao.class);
        registerDaoClass(PirDefaultDao.class);
        registerDaoClass(CatEyeServiceInfoDao.class);
        registerDaoClass(BleLockServiceInfoDao.class);
        registerDaoClass(GatewayServiceInfoDao.class);
        registerDaoClass(GatewayLockRecordDao.class);
        registerDaoClass(GatewayLockBaseInfoDao.class);
        registerDaoClass(GatewayLockPwdDao.class);
        registerDaoClass(GatewayLockAlarmEventDaoDao.class);
        registerDaoClass(DBOpenLockRecordDao.class);
        registerDaoClass(HistoryInfoDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
