package com.kaadas.lock.utils.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kaadas.lock.utils.greenDao.bean.HistoryInfo;

import com.kaadas.lock.utils.greenDao.db.HistoryInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyInfoDaoConfig;

    private final HistoryInfoDao historyInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyInfoDaoConfig = daoConfigMap.get(HistoryInfoDao.class).clone();
        historyInfoDaoConfig.initIdentityScope(type);

        historyInfoDao = new HistoryInfoDao(historyInfoDaoConfig, this);

        registerDao(HistoryInfo.class, historyInfoDao);
    }
    
    public void clear() {
        historyInfoDaoConfig.clearIdentityScope();
    }

    public HistoryInfoDao getHistoryInfoDao() {
        return historyInfoDao;
    }

}
