@startuml
title 安卓蓝牙队列逻辑

Event->Filter: 事件(UI触发/\n蓝牙上报)产生指令
SendQueue->SendQueue:
WaitQueue->WaitQueue:
Ble->Ble:
alt  确认帧
Filter->SendQueue:
else 非确认帧
        alt 下列情况，优先级由上到下
          Filter->Discard: WaitQueue 个数大于4
          Filter->Discard: WaitQueue 存在此指令
          Filter->Discard: SendQueue 存在此指令
       else  添加进等待指令
          Filter->WaitQueue:添加
          alt  当前无等待返回指令
             WaitQueue-> SendQueue: 第一个CMD加入SendQueue
          else 当前有等待执行完的指令
            WaitQueue->WaitQueue: 等待
          end
       end
end

SendQueue ->SendQueue:  每隔100ms发送一个CMD
SendQueue->Ble:  发送指令给蓝牙
    alt  非确认帧
        WaitQueue->WaitQueue: 等待
        Ble->WaitQueue:返回数据
        alt   是当前等待返回指令的返回数据
            WaitQueue-> SendQueue: 第一个CMD加入SendQueue
        else  不是当前等待返回指令的返回数据
            WaitQueue->WaitQueue:等待
            alt   一直没收到返回数据,超过五秒
             WaitQueue-> SendQueue: 第一个CMD加入SendQueue
            else
            end
        end
    else  确认帧
    end

@enduml
